{
  "projectName": "adventure-movie-app",
  "files": {
    "docker-compose.yml": "version: '3.8'\n\nservices:\n  mongodb:\n    image: mongo:latest\n    container_name: mongodb\n    ports:\n      - \"27017:27017\"\n    environment:\n      MONGO_INITDB_DATABASE: adventure_db\n\n  backend:\n    build: ./backend\n    container_name: movie-backend\n    ports:\n      - \"8080:8080\"\n    environment:\n      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/adventure_db\n    depends_on:\n      - mongodb\n\n  frontend:\n    build: ./frontend\n    container_name: movie-frontend\n    ports:\n      - \"80:80\"\n    depends_on:\n      - backend",
    ".github/workflows/ci.yml": "name: Deploy Adventure Movie App\n\non:\n  push:\n    branches: [ \"main\" ]\n\njobs:\n  build-and-deploy:\n    runs-on: ubuntu-latest\n\n    steps:\n    - name: Checkout Code\n      uses: actions/checkout@v3\n\n    - name: Set up Docker Buildx\n      uses: docker/setup-buildx-action@v2\n\n    - name: Log in to Docker Hub\n      uses: docker/login-action@v2\n      with:\n        username: ${{ secrets.DOCKER_USERNAME }}\n        password: ${{ secrets.DOCKER_PASSWORD }}\n\n    - name: Build and Push Images\n      run: |\n        docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-backend:latest ./backend\n        docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-frontend:latest ./frontend\n        docker push ${{ secrets.DOCKER_USERNAME }}/movie-backend:latest\n        docker push ${{ secrets.DOCKER_USERNAME }}/movie-frontend:latest\n\n    - name: Deploy to Server via SSH\n      uses: appleboy/ssh-action@v0.1.10\n      with:\n        host: ${{ secrets.SERVER_HOST }}\n        username: ${{ secrets.SERVER_USER }}\n        key: ${{ secrets.SSH_PRIVATE_KEY }}\n        script: |\n          cd /var/www/adventure-movie-app\n          docker-compose pull\n          docker-compose up -d --remove-orphans",
    "backend/Dockerfile": "FROM maven:3.9-eclipse-temurin-17 AS build\nWORKDIR /app\nCOPY pom.xml .\nCOPY src ./src\nRUN mvn clean package -DskipTests\n\nFROM eclipse-temurin:17-jre\nWORKDIR /app\nCOPY --from=build /app/target/*.jar app.jar\nEXPOSE 8080\nENTRYPOINT [\"java\", \"-jar\", \"app.jar\"]",
    "backend/src/main/java/com/adventure/movie/model/Movie.java": "package com.adventure.movie.model;\n\nimport org.springframework.data.annotation.Id;\nimport org.springframework.data.mongodb.core.mapping.Document;\n\n@Document(collection = \"movies\")\npublic class Movie {\n    @Id\n    private String id;\n    private String title;\n    private String genre;\n    private String description;\n\n    public Movie() {}\n\n    public Movie(String title, String genre, String description) {\n        this.title = title;\n        this.genre = genre;\n        this.description = description;\n    }\n\n    public String getId() { return id; }\n    public String getTitle() { return title; }\n    public void setTitle(String title) { this.title = title; }\n    public String getGenre() { return genre; }\n    public void setGenre(String genre) { this.genre = genre; }\n    public String getDescription() { return description; }\n    public void setDescription(String description) { this.description = description; }\n}",
    "backend/src/main/java/com/adventure/movie/repository/MovieRepository.java": "package com.adventure.movie.repository;\n\nimport com.adventure.movie.model.Movie;\nimport org.springframework.data.mongodb.repository.MongoRepository;\nimport java.util.List;\n\npublic interface MovieRepository extends MongoRepository<Movie, String> {\n    List<Movie> findByGenre(String genre);\n}",
    "backend/src/main/java/com/adventure/movie/controller/MovieController.java": "package com.adventure.movie.controller;\n\nimport com.adventure.movie.model.Movie;\nimport com.adventure.movie.repository.MovieRepository;\nimport org.springframework.web.bind.annotation.*;\nimport java.util.List;\n\n@RestController\n@RequestMapping(\"/api/movies\")\n@CrossOrigin(origins = \"*\")\npublic class MovieController {\n    private final MovieRepository repository;\n\n    public MovieController(MovieRepository repository) {\n        this.repository = repository;\n    }\n\n    @GetMapping\n    public List<Movie> getAllMovies() {\n        return repository.findAll();\n    }\n\n    @PostMapping\n    public Movie addMovie(@RequestBody Movie movie) {\n        return repository.save(movie);\n    }\n}",
    "frontend/Dockerfile": "FROM nginx:alpine\nCOPY index.html /usr/share/nginx/html/index.html\nEXPOSE 80",
    "frontend/index.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>Adventure Movies</title>\n</head>\n<body>\n    <h1>Adventure Movie Catalog</h1>\n    <ul id=\"movie-list\"></ul>\n\n    <script>\n        async function fetchMovies() {\n            const res = await fetch('/api/movies');\n            const movies = await res.json();\n            const list = document.getElementById('movie-list');\n            list.innerHTML = movies.map(m => `<li><strong>${m.title}</strong>: ${m.description}</li>`).join('');\n        }\n        fetchMovies();\n    </script>\n</body>\n</html>"
  }
}